package org.ppke.itk.hj.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "purchase")
@NamedQueries(value =
{ @NamedQuery(name = "getOrdersByUsername", query = "SELECT o FROM Order o join fetch o.customer c left join fetch o.products where c.username like :username") }
)	
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7695791152659879810L;
	
	public static final String getOrdersByUsername = "getOrdersByUsername";
	
	@Id
	@Column(name = "uid", unique = true, nullable = false)
	@SequenceGenerator(name="order_seq",sequenceName="order_seq", allocationSize=100)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="order_seq")
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	private Customer customer;
	
    @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", length = 29)
	private Date orderDate;
	
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "purchase2product", joinColumns = { 
			@JoinColumn(name = "purchase_ID", referencedColumnName="uid") }, 
			inverseJoinColumns = { @JoinColumn(name = "PRODUCT_ID", 
					referencedColumnName="uid") })
	private List<Product> products = new ArrayList<>();
	

	public Order() {
		this.orderDate = new Date();
	}


	public Order(Customer customer, Date orderDate) {
		this.customer = customer;
		this.orderDate = orderDate;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}


	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	
	public List<Product> getProducts() {
		return products;
	}


	public void setProducts(List<Product> products) {
		this.products = products;
	}
	




}
